architecture: DQN

train:
  name: DQN
  expname: exp-neg-decay-b128-emb-majorkey
  total_timesteps: 1500000
  log_interval: 1000
  checkpoint_freq: 100000
  eval_freq: 100000
  evaluation_n: 250
  n_envs: 4

model:
  policy: MultiInputPolicy
  learning_rate: 0.0003
  seed: 37
  kwargs:
    batch_size: 128
    tau: 0.5
    gamma: 0.99
    train_freq: 4
    tensorboard_log: ./logs/tb/
    verbose: 1
    policy_kwargs:
      net_arch: [128, 128]
      features_extractor_class: CustomCombinedExtractor
      features_extractor_kwargs: {}
